# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('norad_id',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='NORAD catalog number')),
                ('name', models.CharField(max_length=100)),
                ('tle', models.CharField(max_length=164, verbose_name='two-line element')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution', models.CharField(blank=True, max_length=100)),
                ('audio', models.FileField(upload_to=b'')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satsound.Satellite')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteTrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rise_time', models.DateTimeField(verbose_name='rise time')),
                ('rise_azimuth', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='rise azimuth')),
                ('maxalt_time', models.DateTimeField(verbose_name='maximum altitude time')),
                ('maxalt_altitude',
                 models.DecimalField(decimal_places=6, max_digits=9, verbose_name='maximum altitude')),
                ('set_time', models.DateTimeField(verbose_name='set time')),
                ('set_azimuth', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='set azimuth')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satsound.Satellite')),
            ],
        ),
    ]
