# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 17:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('satsound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitetrajectory',
            name='observer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='satsound.Observer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satellite',
            name='tle',
            field=models.CharField(blank=True, max_length=164, verbose_name='two-line element'),
        ),
    ]
