# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('satsound', '0002_auto_20161110_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='ip',
            field=models.CharField(default='127.0.0.1:54321', max_length=40),
        ),
        migrations.AddField(
            model_name='observer',
            name='trajectory_window',
            field=models.IntegerField(default=24, verbose_name='hours of trajectories'),
        ),
    ]
