# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('satsound', '0003_auto_20161218_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satellitetrajectory',
            options={'verbose_name_plural': 'satellite trajectories'},
        ),
        migrations.AddField(
            model_name='observer',
            name='elevation',
            field=models.IntegerField(default=0, verbose_name='elevation in meters'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='trajectory_window',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='hours of trajectories'),
        ),
    ]
