# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('satsound', '0007_auto_20170115_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='timezone',
            field=models.CharField(default=b'Europe/London', max_length=100),
        ),
    ]
