# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('satsound', '0008_observer_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteaudio',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satelliteaudio',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'recorded transmission'), (2, 'interpretation')],
                                                   default=1),
            preserve_default=False,
        ),
    ]
