"""
Django settings for apman project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-!4xsmf2n-5+j3q5w*1&(z&dpa17t9dal950!=9qxl4u$-s!^h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
USE_S3 = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'satsound.apps.SatsoundConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'storages',
    'django_cleanup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apman.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ap',
        'USER': 'ap',
        'PASSWORD': '0verourH#$Ds',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

SPACETRACK_IDENTITY = 'HNeilson'
SPACETRACK_PASSWORD = 'lumela41134990khotso'

AUDIO_TYPES = (
    'audio/aac',  # .aac
    'audio/basic',  # .au .snd
    'audio/mid',  # .mid .rmi
    'audio/mpeg',  # .mp1 .mp2 .mp3 .mpg .mpeg
    'audio/mp4',  # .mp4 .m4a
    'audio/ogg',  # .oga .ogg
    'audio/vorbis',  # .ogg
    'audio/vnd.wav',  # .wav
    'audio/wav',  # .wav
    'audio/wave',  # .wav
    'audio/x-wav',  # .wav
    'audio/x-pn-wav',  # .wav
    'audio/webm',  # .webm
    'audio/x-aiff',  # .aif .aifc .aiff
)
MAX_AUDIOFILE_SIZE = 10 * 1024 * 1024  # 10 mb

MAX_IMMINENCE = 1  # number of hours to consider 'recent' when comparing audio timestamps to trajectory rise times
TRAJECTORY_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'audio')
MEDIA_URL = '/audio/'

try:
    from settings_dev import *
except ImportError as e:
    pass

AWS_ACCESS_KEY_ID = 'AKIAIHC73V64GGSR42AA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'spaudio'
AWS_QUERYSTRING_AUTH = False
S3_URL = 'https://s3.amazonaws.com/%s/' % AWS_STORAGE_BUCKET_NAME

if USE_S3:
    DEFAULT_FILE_STORAGE = 'apman.s3utils.MediaRootS3BotoStorage'
    MEDIA_URL = '%s%s' % (S3_URL, 'media/')
